sudo: false
language: go
go:
    - 1.4
notifications:
    irc:
        channels:
            - "irc.mozilla.org#heka"
addons:
    apt:
        packages:
        - protobuf-compiler
        - cmake
        - libgeoip-dev
install:
    - . build.sh
script:
    - make test
