[LogstreamerInput]
log_directory = "./log"
file_match = 'test1.log'

[PayloadEncoder]
append_newlines = false

[LogOutput]
message_matcher = "TRUE"
encoder = "PayloadEncoder"

[DashboardOutput]
ticker_interval = 30